### ISSUE TITLE
NullReference Error at GetPointAt function when t approaches 1

### ISSUE THREAD

**Issue by Gentatsu** [dbrizov/Unity-BezierCurves#2]
For some reason, when I call the GetPointAt function to interpolate along the curve from 0 to 1, when it approaches 1, it gets me a NullReference error. If I go from 1 to 0, it seems to fine. I'm going back and forth between 0 and 1, so it can do 1 loop. This doesn't seem to happen all the time, though, so I'm not sure why it's doing it. Sometimes it'll do it after 2 loops, others after 1.

**Comment by dbrizov** [comment]
Hmm, it must be some edge case.
Can you provide me with the exact curve, so I can test it and see what the
problem is?

Cheers,
Denis

**Comment by Gentatsu** [comment]
Sure. It seems to fix it (not tested thoroughly) when I change the line `if (close && p1 == null)` to `if (close || p1 == null)`, since it seems to not be setting p1 or p2 in `GetPointAt`. 

For the curve, I have:

Point0: 
pos : x: 5.226903, y: -1.671023, z: -1.05361
Handle1: x: 0.242362, y : -0.4567208, z: 0.2865171
Handle2: x: -0.242362, y: 0.4567208, z: -0.2865171

Point1:
pos: x: 1.34, y: -1.65, z: -6.24
Handle1: x: 0.1552831, y: 0.1096056, z: 0.225625
Handle2: x: -0.5023321, y: -0.7018181, z: -0.5146093

I'm running 2017.1.1

I've tried changing the curve a bunch, and clamping my values to 0 and 1 before passing them to your function (although you seem to already test for it).
